/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokmalzememodul.Forms;

import stokmalzememodul.Malzeme;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author abatox
 */
public class MalzemeEkleForm extends FormLayout {

    /**
     * Creates new form MalzemeEkleForm
     */
    public MalzemeEkleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adLabel = new javax.swing.JLabel();
        markaLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        agirlikLabel = new javax.swing.JLabel();
        fiyatLabel = new javax.swing.JLabel();
        adTextField = new javax.swing.JTextField();
        markaTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        agirlikTextField = new javax.swing.JTextField();
        fiyatTextField = new javax.swing.JTextField();
        ekleButton = new javax.swing.JButton();
        geriDonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adLabel.setText("Malzeme Ad");

        markaLabel.setText("Malzeme Marka");

        modelLabel.setText("Malzeme Model(varsa)");

        agirlikLabel.setText("Malzeme Ağırlık");

        fiyatLabel.setText("Malzeme Fiyat");

        ekleButton.setText("Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        geriDonButton.setText("Geri Dön");
        geriDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(geriDonButton)
                        .addGap(18, 18, 18)
                        .addComponent(ekleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agirlikLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fiyatLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modelLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(markaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(adLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agirlikTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(modelTextField)
                            .addComponent(markaTextField)
                            .addComponent(adTextField)
                            .addComponent(fiyatTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agirlikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agirlikLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekleButton)
                    .addComponent(geriDonButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed
        String ad = adTextField.getText();
        String marka = markaTextField.getText();
        String model = modelTextField.getText();
        double agirlik=0, fiyat=0;
        
        System.out.println(ad);
        
        if (ad.isEmpty()) {
            showMessageDialog(null, "Hatalı ad girişi.");
            adTextField.setText("");
            return;
        }
        
        if (marka.isEmpty()) {
            showMessageDialog(null, "Hatalı marka girişi. ");
            return;
        }
        
        try {
            agirlik = Double.parseDouble(agirlikTextField.getText());
            fiyat = Double.parseDouble(fiyatTextField.getText());
        } catch(Exception e) {
            showMessageDialog(null, "Hatalı ağırlık veya fiyat girişi.");
            agirlikTextField.setText("");
            fiyatTextField.setText("");
            return;
        }
        
        Malzeme malzeme = new Malzeme(ad, marka, model, agirlik, fiyat);
        malzeme.Ekle();
        adTextField.setText("");
        markaTextField.setText("");
        modelTextField.setText("");
        agirlikTextField.setText("");
        fiyatTextField.setText("");
        showMessageDialog(null, "İşlem gerçekleştirildi.");
    }//GEN-LAST:event_ekleButtonActionPerformed

    private void geriDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonButtonActionPerformed
        MalzemeForm form = new MalzemeForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriDonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeEkleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeEkleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLabel;
    private javax.swing.JTextField adTextField;
    private javax.swing.JLabel agirlikLabel;
    private javax.swing.JTextField agirlikTextField;
    private javax.swing.JButton ekleButton;
    private javax.swing.JLabel fiyatLabel;
    private javax.swing.JTextField fiyatTextField;
    private javax.swing.JButton geriDonButton;
    private javax.swing.JLabel markaLabel;
    private javax.swing.JTextField markaTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    // End of variables declaration//GEN-END:variables
}
