package stokmalzememodul.Forms;

import static javax.swing.JOptionPane.showMessageDialog;
import stokmalzememodul.Malzeme;

public class MalzemeGuncelleForm extends FormLayout {
    private Malzeme malzeme = null;
    /**
     * Creates new form MalzemeGuncelleForm
     */
    public MalzemeGuncelleForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geriDonButton = new javax.swing.JButton();
        malzemeIdTextField = new javax.swing.JTextField();
        malzemeIdLabel = new javax.swing.JLabel();
        bilgileriAktarButton = new javax.swing.JButton();
        modelLabel = new javax.swing.JLabel();
        fiyatTextField = new javax.swing.JTextField();
        markaTextField = new javax.swing.JTextField();
        agirlikTextField = new javax.swing.JTextField();
        adTextField = new javax.swing.JTextField();
        fiyatLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        adLabel = new javax.swing.JLabel();
        markaLabel = new javax.swing.JLabel();
        agirlikLabel = new javax.swing.JLabel();
        guncelleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        geriDonButton.setText("Geri Dön");
        geriDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonButtonActionPerformed(evt);
            }
        });

        malzemeIdLabel.setText("Malzeme Id");

        bilgileriAktarButton.setText("Malzeme Bilgilerini Aktar");
        bilgileriAktarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgileriAktarButtonActionPerformed(evt);
            }
        });

        modelLabel.setText("Malzeme Model(varsa)");

        fiyatLabel.setText("Malzeme Fiyat");

        adLabel.setText("Malzeme Ad");

        markaLabel.setText("Malzeme Marka");

        agirlikLabel.setText("Malzeme Ağırlık");

        guncelleButton.setText("Güncelle");
        guncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(geriDonButton)
                        .addGap(18, 18, 18)
                        .addComponent(guncelleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(bilgileriAktarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(modelLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(agirlikLabel)
                                            .addComponent(adLabel)
                                            .addComponent(markaLabel)
                                            .addComponent(malzemeIdLabel)
                                            .addComponent(fiyatLabel))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fiyatTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(agirlikTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(modelTextField)
                                        .addComponent(malzemeIdTextField)
                                        .addComponent(adTextField)
                                        .addComponent(markaTextField)))))))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malzemeIdLabel)
                    .addComponent(malzemeIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bilgileriAktarButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agirlikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agirlikLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geriDonButton)
                    .addComponent(guncelleButton))
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleButtonActionPerformed
        if (malzeme == null) {
            showMessageDialog(null, "Hatalı id girişi.");
            return;
        }
        
        String ad = adTextField.getText();
        String marka = markaTextField.getText();
        String model = modelTextField.getText();
        double agirlik=0, fiyat=0;
        
        System.out.println(ad);
        
        if (ad.isEmpty()) {
            showMessageDialog(null, "Hatalı ad girişi.");
            adTextField.setText("");
            return;
        }
        
        if (marka.isEmpty()) {
            showMessageDialog(null, "Hatalı marka girişi. ");
            return;
        }
        
        try {
            agirlik = Double.parseDouble(agirlikTextField.getText());
            fiyat = Double.parseDouble(fiyatTextField.getText());
        } catch(Exception e) {
            showMessageDialog(null, "Hatalı ağırlık veya fiyat girişi.");
            agirlikTextField.setText("");
            fiyatTextField.setText("");
            return;
        }
        
        malzeme.SetAd(adTextField.getText());
        malzeme.SetAgirlik(Double.parseDouble(agirlikTextField.getText()));
        malzeme.SetFiyat(Double.parseDouble(fiyatTextField.getText()));
        malzeme.SetMarka(markaTextField.getText());
        malzeme.SetModel(modelTextField.getText());
        
        malzeme.Guncelle();
        
        showMessageDialog(null, "Güncelleme başarılı.");
    }//GEN-LAST:event_guncelleButtonActionPerformed

    private void bilgileriAktarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgileriAktarButtonActionPerformed
        int malzemeId = 0;
        try {
            malzemeId = Integer.parseInt(malzemeIdTextField.getText());
        } catch(Exception e) {
            showMessageDialog(null, "Hatalı id girişi.");
            malzemeIdTextField.setText("");
            malzeme = new Malzeme(malzemeId);
            adTextField.setText("");
            markaTextField.setText("");
            modelTextField.setText("");
            agirlikTextField.setText("");
            fiyatTextField.setText("");
            malzeme = null;
            return;
        }
        malzeme = new Malzeme(malzemeId);
        adTextField.setText(malzeme.GetAd());
        markaTextField.setText(malzeme.GetMarka());
        modelTextField.setText(malzeme.GetModel());
        agirlikTextField.setText(Double.toString(malzeme.GetAgirlik()));
        fiyatTextField.setText(Double.toString(malzeme.GetFiyat()));
    }//GEN-LAST:event_bilgileriAktarButtonActionPerformed

    private void geriDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonButtonActionPerformed
        MalzemeForm form = new MalzemeForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriDonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeGuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeGuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeGuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeGuncelleForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeGuncelleForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adLabel;
    private javax.swing.JTextField adTextField;
    private javax.swing.JLabel agirlikLabel;
    private javax.swing.JTextField agirlikTextField;
    private javax.swing.JButton bilgileriAktarButton;
    private javax.swing.JLabel fiyatLabel;
    private javax.swing.JTextField fiyatTextField;
    private javax.swing.JButton geriDonButton;
    private javax.swing.JButton guncelleButton;
    private javax.swing.JLabel malzemeIdLabel;
    private javax.swing.JTextField malzemeIdTextField;
    private javax.swing.JLabel markaLabel;
    private javax.swing.JTextField markaTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    // End of variables declaration//GEN-END:variables
}
