package stokmalzememodul.Forms;

import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import stokmalzememodul.Malzeme;

public class MalzemeAraForm extends FormLayout {

    /**
     * Creates new form MalzemeAraForm
     */
    public MalzemeAraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fiyatTextField = new javax.swing.JTextField();
        markaTextField = new javax.swing.JTextField();
        agirlikTextField = new javax.swing.JTextField();
        adTextField = new javax.swing.JTextField();
        fiyatLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        adLabel = new javax.swing.JLabel();
        markaLabel = new javax.swing.JLabel();
        agirlikLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        araButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BulunanMalzeme = new javax.swing.JTable();
        geriDonButton = new javax.swing.JButton();
        tabloTemizleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Malzeme arama koşulları");

        fiyatLabel.setText("Malzeme Fiyat");

        adLabel.setText("Malzeme Ad");

        markaLabel.setText("Malzeme Marka");

        agirlikLabel.setText("Malzeme Ağırlık");

        modelLabel.setText("Malzeme Model(varsa)");

        araButton.setText("Ara");
        araButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araButtonActionPerformed(evt);
            }
        });

        BulunanMalzeme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ad", "Marka", "Model", "Agirlik", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BulunanMalzeme);

        geriDonButton.setText("Geri Dön");
        geriDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriDonButtonActionPerformed(evt);
            }
        });

        tabloTemizleButton.setText("Tablo Temizle");
        tabloTemizleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabloTemizleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(geriDonButton)
                            .addGap(18, 18, 18)
                            .addComponent(tabloTemizleButton)
                            .addGap(18, 18, 18)
                            .addComponent(araButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(modelLabel)
                                    .addGap(16, 16, 16))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(markaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(agirlikLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fiyatLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(agirlikTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(modelTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(fiyatTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(markaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(adTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                .addComponent(jLabel1)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agirlikTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agirlikLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fiyatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(araButton)
                    .addComponent(geriDonButton)
                    .addComponent(tabloTemizleButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araButtonActionPerformed
        String ad = adTextField.getText();
        String marka = markaTextField.getText();
        String model = modelTextField.getText();
        double agirlik=0, fiyat=0;
        
        try {
            String agirlikText = agirlikTextField.getText();
            String fiyatText = fiyatTextField.getText();
            
            if (!agirlikText.isEmpty())
                agirlik = Double.parseDouble(agirlikText);
            if (!fiyatText.isEmpty())
                fiyat = Double.parseDouble(fiyatText);
        } catch(Exception e) {
            showMessageDialog(null, "Hatalı ağırlık veya fiyat girişi.");
            agirlikTextField.setText("");
            fiyatTextField.setText("");
            return;
        }
        Malzeme malzeme = new Malzeme();
        
        if (!ad.isEmpty()) {
            malzeme.SetAd(ad);
        }
        if (!marka.isEmpty()) {
            malzeme.SetMarka(marka);
        }
        if (!model.isEmpty()) {
            malzeme.SetModel(model);
        }
        if (agirlik != 0) {
            malzeme.SetAgirlik(agirlik);
        }
        if (fiyat != 0) {
            malzeme.SetFiyat(fiyat);
        }
        
        List<Malzeme> BulunanMalzemeler = malzeme.Ara();
        
        if (BulunanMalzemeler == null) {
            showMessageDialog(null, "Malzeme bulunamadı.");
            return;
        }
        
        DefaultTableModel tblModel = (DefaultTableModel) BulunanMalzeme.getModel();
        
        for (Malzeme m : BulunanMalzemeler) {
            Object data[] = {m.GetId(), m.GetAd(), m.GetMarka(),
                            m.GetModel(), m.GetAgirlik(), m.GetFiyat()};
            
            System.out.println(m.GetId());
            
            tblModel.addRow(data);
        }
    }//GEN-LAST:event_araButtonActionPerformed

    private void geriDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriDonButtonActionPerformed
        MalzemeForm form = new MalzemeForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriDonButtonActionPerformed

    private void tabloTemizleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabloTemizleButtonActionPerformed
        DefaultTableModel tblModel = (DefaultTableModel) BulunanMalzeme.getModel();
        tblModel.setRowCount(0);
    }//GEN-LAST:event_tabloTemizleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeAraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeAraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeAraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeAraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeAraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BulunanMalzeme;
    private javax.swing.JLabel adLabel;
    private javax.swing.JTextField adTextField;
    private javax.swing.JLabel agirlikLabel;
    private javax.swing.JTextField agirlikTextField;
    private javax.swing.JButton araButton;
    private javax.swing.JLabel fiyatLabel;
    private javax.swing.JTextField fiyatTextField;
    private javax.swing.JButton geriDonButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel markaLabel;
    private javax.swing.JTextField markaTextField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JButton tabloTemizleButton;
    // End of variables declaration//GEN-END:variables
}
