/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stokmalzememodul.Forms;

/**
 *
 * @author abatox
 */
public class MalzemeForm extends FormLayout {

    /**
     * Creates new form MalzemeForm
     */
    public MalzemeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnaMenuButton = new javax.swing.JButton();
        MalzemeEkleButton = new javax.swing.JButton();
        MalzemeCikarButton = new javax.swing.JButton();
        MalzemeAraButton = new javax.swing.JButton();
        MalzemeGuncelleButton = new javax.swing.JButton();
        MalzemeListeleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        AnaMenuButton.setText("Ana Menüye Dön");
        AnaMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnaMenuButtonActionPerformed(evt);
            }
        });

        MalzemeEkleButton.setText("Malzeme Ekle");
        MalzemeEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeEkleButtonActionPerformed(evt);
            }
        });

        MalzemeCikarButton.setText("Malzeme Çıkar");
        MalzemeCikarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeCikarButtonActionPerformed(evt);
            }
        });

        MalzemeAraButton.setText("Malzeme Ara");
        MalzemeAraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeAraButtonActionPerformed(evt);
            }
        });

        MalzemeGuncelleButton.setText("Malzeme Güncelle");
        MalzemeGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeGuncelleButtonActionPerformed(evt);
            }
        });

        MalzemeListeleButton.setText("Malzeme Listele");
        MalzemeListeleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeListeleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 465, Short.MAX_VALUE)
                        .addComponent(AnaMenuButton))
                    .addComponent(MalzemeEkleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MalzemeCikarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MalzemeAraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MalzemeGuncelleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MalzemeListeleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MalzemeEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MalzemeGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MalzemeCikarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MalzemeAraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MalzemeListeleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(AnaMenuButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnaMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnaMenuButtonActionPerformed
        AnaForm form = new AnaForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_AnaMenuButtonActionPerformed

    private void MalzemeEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeEkleButtonActionPerformed
        MalzemeEkleForm form = new MalzemeEkleForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_MalzemeEkleButtonActionPerformed

    private void MalzemeGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeGuncelleButtonActionPerformed
        MalzemeGuncelleForm form = new MalzemeGuncelleForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_MalzemeGuncelleButtonActionPerformed

    private void MalzemeCikarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeCikarButtonActionPerformed
        MalzemeCikarForm form = new MalzemeCikarForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_MalzemeCikarButtonActionPerformed

    private void MalzemeAraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeAraButtonActionPerformed
        MalzemeAraForm form = new MalzemeAraForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_MalzemeAraButtonActionPerformed

    private void MalzemeListeleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeListeleButtonActionPerformed
        MalzemeListeleForm form = new MalzemeListeleForm();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_MalzemeListeleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MalzemeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnaMenuButton;
    private javax.swing.JButton MalzemeAraButton;
    private javax.swing.JButton MalzemeCikarButton;
    private javax.swing.JButton MalzemeEkleButton;
    private javax.swing.JButton MalzemeGuncelleButton;
    private javax.swing.JButton MalzemeListeleButton;
    // End of variables declaration//GEN-END:variables
}
